version: '3'

services:
 labs:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes:
     [ "./backend_labs:/opt/backend_labs" ]
   environment:
     PORT: "5000"
     FLASK_DEBUG: True
   ports:
     - "5000:5000"